=== Broncko/Savant/Savant/conf/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT config (configurations)+>
<!ELEMENT configurations (section)+>
<!ELEMENT section (member)+>
<!ATTLIST section
    name NMTOKEN #REQUIRED>
<!ELEMENT member (#PCDATA)>
<!ATTLIST member
    name NMTOKEN #REQUIRED>

=== Broncko/Savant/Savant/conf/Savant/Service/CBitly.conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config>
    <configurations>
	<section name="default">
            <member name="login">broncko</member>
            <member name="apikey">R_57d500ca82ec1ee06d4fddae7f3b66e1</member>
            <member name="resturl"><![CDATA[http://api.bit.ly/shorten?version=2.0.1&longUrl=%s&login=%s&apiKey=%s]]></member>
	</section>
        <section name="other">
            <member name="login">hendrik</member>
            <member name="apikey">ldsfjlsdfjldsflsdaf√∂jl</member>
            <member name="resturl">www.bronckopedia.de</member>
        </section>
    </configurations>
</config>
